default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: petite_denki_development
  host: /tmp
  port: 5432

test:
  <<: *default
  database: petite_denki_test

production:
  <<: *default
  database: petite_denki_production
  username: petite_denki
  password: <%= ENV["petite_denki_DATABASE_PASSWORD"] %>
